spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/msa-example
    username: sa
    password: '{cipher}AQA0TrKjVKL75srBa39i/0oqvSrsF7a5S1kt690qUGabLJSMRIXcwUsvCgoJGXN3eBwZuf6XpPl8gkaRTEapaGv9OUfU7EoRy18a5oSTK8Fnzhcu88TPgn18jHSn/k4rf/P+MLhMr6EpgekVefG9jolmNM7fqdwEoyJvyUcGWGdMDyDhorN+K5VyYoI2KoM/3pnuD7yW+eP2F5R+YGl04Y5Iob3dr1mjtHBYH/YoDS5N/Ar2GIMbjoH1LS12sJYi/vIoPhAN13Jj+nsjrkO+BXMM+YKFtifM4mrJs9oY5jmo6R8rPb4K0PrKBTgZWeNzlNbKXAnC8VeSz57KG8WJxU3Cfe0IC/x2PBIW5FtGKy2nxNitfkvhtVCRkPdFOh8xtfU='

token:
  expiration_time: 86400000

gateway:
  ip: http://localhost:8000

order_service:
  url: http://order-service/order-service/orders/%s
  exception:
    orders_is_empty: The member's order is empty.


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000