spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/members?serverTimezone=Asia/Seoul
    username: test
    password: '{cipher}AQBolrv3RIiE5IEoiwbPSE52uPlIFopCoMgIuK73cKokvEGSfOb/uUBUbZ6RvXIdVx2YzVf/F0z7M65CHCVtzu/K0nsGIr0ICwmUtSX8BeWtEOlfn2RQPc6ZjXZDCLjFz8B4l0pYkOo65pR8BSPPEB6qskoU845RVh9rD7/almlCd36WHRZf9BPkkrGWf/a/bitjJcaT7WehOAPhUUOS6dGaLn/IqT/dHy/iUuT6Acw0xqhahulMcFWU5W26scGnUaOzmsrlE6YsX0UIG7OP6ly5RX5SdvndsRHc8iadqHv6Ve3h4uudObCxc2CUcig4thW67XffP6VvlOPHCZuqM/bimOGBn61kWi0Oz3C3CBaZ6X/2XHZeDNs340ZbHgZzqsc='

token:
  expiration_time: 86400000

gateway:
  ip: http://172.18.0.5:8000

order_service:
  url: http://order-service/order-service/orders/%s
  exception:
    orders_is_empty: The member's order is empty.


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000