spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysql-container:3306/mydb?serverTimezone=Asia/Seoul&useSSL=false
    username: root
    password: '{cipher}AQAm5r0C0ZrYYbcMiCipW/LzRqDmuvLlZNuDKrxGx6Qtj4+jb5phN08aVJBuPuSIpDmVyKydWzD/fMrE0jK6DOpW0mpqM1AoJdjFUwxh+fRPmOBsgQKr7oEL/0mWp/hWd9WSeBFjqz5k5Xhx3/DkVuHX6BJcTeu4CAAYhdJAN49BKajGzKCI0vnrGV+ig63cNDlpl0S0chNp4StnBxZWZx0XOCDQnjn2GeWhAq2ONPzh7m2IJw87aPSUW1zWBAE8cP/E0Pt5vYw1/Oer/bFSPfyqa1WK0x0GtZPHMJ67RHUO2SCyGafIXYq+82n6PLO/ai7MjMf05B1miKaGQzvhyAyclVvEquWyDVPWVum5gXVz4Syd/ZVZc47vObkbEtuDD9Q='

token:
  expiration_time: 86400000

gateway:
  ip: http://172.18.0.5:8000

order_service:
  url: http://order-service/order-service/orders/%s
  exception:
    orders_is_empty: The member's order is empty.


feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000